# Generated by Django 4.0.4 on 2022-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
